FROM python

WORKDIR /app/downloader

RUN apt-get -y update 

RUN pip3 install flask fask-sqlalchemy


    # && apt-get install -y cmake \
    # && apt-get install -y liblog4c-dev \
    # && wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl \
    # && chmod a+rx /usr/local/bin/youtube-dl \
    # && apt-get install -y default-libmysqlclient-dev \
    # && apt-get install -y default-mysql-client \
    # && apt-get install -y libconfig-dev \
    # && apt-get install -y ffmpeg

COPY ./ ./

# CMD [ "ping","google.com" ]