version: '3'
services:
  download-manager:
    restart: always
    build: .
    ports: 
      - "5000:5000"
    volumes:
      - './downloads:/app/downloader/downloads'
      - /etc/localtime:/etc/localtime:ro
      - './data:/app/downloader/instance'
      - './logs:/app/downloader/logs'
    environment:
      - SECRET_KEY=your_secret_key
      - DASHBOARD_PASSWORD=admin
      - DASHBOARD_USERNAME=admin