name: Docker Image CI

on:
  push:
    tags:
      - '*.*'
    
jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Run Buildx
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm64,linux/arm/v7 \
          -t lasithih/vortex:latest  -t lasithih/vortex:${{ env.RELEASE_VERSION }} \
          --push .